

CREATE DATABASE IF NOT EXISTS PAPELARIA;

USE PAPELARIA;

CREATE TABLE CLIENTE(
		NOMECLIENTE VARCHAR (200) NOT NULL,
        CPF DECIMAL (11) NOT NULL,
        ENDERECOC VARCHAR (200),
        EMAIL VARCHAR (200) NOT NULL,
        
        CONSTRAINT CLIENTE_PK PRIMARY KEY (CPF)
) ENGINE = INNODB;

CREATE TABLE FUNCIONARIO(

		MATRICULA INT (8) NOT NULL,
        NOMEFUNCIONARIO VARCHAR (200) NOT NULL,
        FUNCAO VARCHAR (30) NOT NULL,
        EMAIL VARCHAR (200) NOT NULL,
        
        CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (MATRICULA)
)ENGINE = INNODB;

CREATE TABLE FORNECEDOR (

		CNPJ DECIMAL (14) NOT  NULL,
        NOMEFORNECEDOR VARCHAR (100) NOT NULL,
        TELEFONE DECIMAL (11) NOT NULL,
        ENDERECOF VARCHAR (200) NOT NULL,
        
        CONSTRAINT FORNECEDOR_PK PRIMARY KEY (CNPJ)
        
) ENGINE = INNODB;

CREATE TABLE PRODUTO (

		CODIGO INT (6) NOT NULL,
        PRECO VARCHAR (5) NOT NULL,
        VALIDADE DATE,
        NOMEPRODUTO VARCHAR (20) NOT NULL,
        DESCRICAO VARCHAR (100) NOT NULL,
        QUANTIDADE INT NOT NULL,
		CNPJ DECIMAL (14) NOT  NULL,
        
    CONSTRAINT PRODUTO_PK PRIMARY KEY (CODIGO),
    CONSTRAINT FORNECEDOR_FK FOREIGN KEY (CNPJ)
        REFERENCES FORNECEDOR (CNPJ)
        ON DELETE CASCADE
) ENGINE = INNODB;